# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_deepLinks(self):
    self.driver.get("https://iac-spa-demo.jonesaws.people.aws.dev/")
    self.driver.set_window_size(550, 691)
    assert self.driver.find_element(By.CSS_SELECTOR, "h2").text == "Welcome to the Demo Single Page App :)"
    self.driver.get("https://iac-spa-demo.jonesaws.people.aws.dev/about")
    assert self.driver.find_element(By.CSS_SELECTOR, "h2").text == "Welcome to the About page"
    self.driver.get("https://iac-spa-demo.jonesaws.people.aws.dev/contact")
    assert self.driver.find_element(By.CSS_SELECTOR, "h2").text == "Welcome to the Contact page"
  
  def test_navMenu(self):
    self.driver.get("https://iac-spa-demo.jonesaws.people.aws.dev/")
    self.driver.set_window_size(550, 691)
    assert self.driver.find_element(By.CSS_SELECTOR, "h2").text == "Welcome to the Demo Single Page App :)"
    self.driver.find_element(By.LINK_TEXT, "About").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "h2").text == "Welcome to the About page"
    self.driver.find_element(By.LINK_TEXT, "Contact").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "h2").text == "Welcome to the Contact page"
    self.driver.find_element(By.LINK_TEXT, "Home").click()
  
